---
apiVersion: xl-deploy/v1
kind: Environments
spec:
- directory: Environments/test
  children:
  - name: aws test
    type: udm.Environment
    members:
    - Infrastructure/aws cloud connection
    dictionaries:
    - Environments/test/aws test configuration
  - name: aws test configuration
    type: udm.Dictionary
    entries:
      env: test
