---
apiVersion: xl-deploy/v1
kind: Infrastructure
spec:
- name: Infrastructure/aws cloud connection
  type: aws.Cloud
  accesskey: aaaaaaa
  accessSecret: bbbbbb
  children:
  - name: eu-west-3
    type: aws.cloudformation.Stack
    region: eu-west-3
